# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateMasterDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateMasterdatabase(object):
    def setupUi(self, CreateMasterdatabase):
        CreateMasterdatabase.setObjectName("CreateMasterdatabase")
        CreateMasterdatabase.resize(932, 893)
        CreateMasterdatabase.setAutoFillBackground(False)
        self.label = QtWidgets.QLabel(CreateMasterdatabase)
        self.label.setGeometry(QtCore.QRect(220, 50, 531, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(CreateMasterdatabase)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 460, 621, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BuildTableButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BuildTableButton.setFont(font)
        self.BuildTableButton.setObjectName("BuildTableButton")
        self.horizontalLayout.addWidget(self.BuildTableButton)
        self.NewTableButton = QtWidgets.QPushButton(self.layoutWidget)
        self.NewTableButton.setObjectName("NewTableButton")
        self.horizontalLayout.addWidget(self.NewTableButton)
        self.CancelButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.StopButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.horizontalLayout.addWidget(self.StopButton)
        self.consoleA = QtWidgets.QTextEdit(CreateMasterdatabase)
        self.consoleA.setGeometry(QtCore.QRect(110, 520, 621, 241))
        self.consoleA.setAutoFillBackground(False)
        self.consoleA.setStyleSheet("color: rgb(0, 0, 0);")
        self.consoleA.setObjectName("consoleA")
        self.label_8 = QtWidgets.QLabel(CreateMasterdatabase)
        self.label_8.setGeometry(QtCore.QRect(110, 500, 141, 16))
        self.label_8.setObjectName("label_8")
        self.textEdit_2 = QtWidgets.QTextEdit(CreateMasterdatabase)
        self.textEdit_2.setGeometry(QtCore.QRect(120, 770, 621, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.layoutWidget1 = QtWidgets.QWidget(CreateMasterdatabase)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 89, 771, 351))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.layoutWidget1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(10, 9, 231, 331))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 329))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 211, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(2, 2, 0, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_2.setObjectName("label_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 9, 231, 331))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 229, 329))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 39, 211, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 211, 31))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 9, 231, 331))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 229, 329))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 39, 211, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_4.addWidget(self.textEdit_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.SizeLimitCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.SizeLimitCombo.setObjectName("SizeLimitCombo")
        self.SizeLimitCombo.addItem("")
        self.SizeLimitCombo.addItem("")
        self.SizeLimitCombo.addItem("")
        self.SizeLimitCombo.addItem("")
        self.SizeLimitCombo.addItem("")
        self.SizeLimitCombo.addItem("")
        self.verticalLayout_4.addWidget(self.SizeLimitCombo)
        self.movieTypeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.movieTypeButton.setObjectName("movieTypeButton")
        self.verticalLayout_4.addWidget(self.movieTypeButton)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 211, 31))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.frame_3)

        self.retranslateUi(CreateMasterdatabase)
        QtCore.QMetaObject.connectSlotsByName(CreateMasterdatabase)

    def retranslateUi(self, CreateMasterdatabase):
        _translate = QtCore.QCoreApplication.translate
        CreateMasterdatabase.setWindowTitle(_translate("CreateMasterdatabase", "Create Master Database"))
        self.label.setText(_translate("CreateMasterdatabase", "Select Drive, Location or File Type Exclusions"))
        self.BuildTableButton.setText(_translate("CreateMasterdatabase", "Rebuild Table"))
        self.NewTableButton.setText(_translate("CreateMasterdatabase", "Create New Table"))
        self.CancelButton.setText(_translate("CreateMasterdatabase", "Cancel"))
        self.StopButton.setText(_translate("CreateMasterdatabase", "Stop Program"))
        self.consoleA.setHtml(_translate("CreateMasterdatabase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("CreateMasterdatabase", "Console Output"))
        self.textEdit_2.setHtml(_translate("CreateMasterdatabase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This screen runs a program that analyses all network mapped drives to identify movie files. It looks for file extensions that match a list maintained in the database. It is possible to exclude drives, folders, part path name, and file typyes before building the data file, The mew table option will rename the existing table and create a new version with the presets selected below, The Console output is recorded in a logging file as well</p></body></html>"))
        self.label_2.setText(_translate("CreateMasterdatabase", "Select Drives to be excluded"))
        self.textEdit_3.setHtml(_translate("CreateMasterdatabase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Windows</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">iocage</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Music</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Photos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pictures</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Program Files</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">$RECYCLE</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sport</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TV Shows</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">UniConverter</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sharpe</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">VIDEO_TS</p></body></html>"))
        self.label_3.setText(_translate("CreateMasterdatabase", "Enter folder names or Path Names. Each item on a new line"))
        self.textEdit_4.setHtml(_translate("CreateMasterdatabase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.jpeg</p></body></html>"))
        self.label_5.setText(_translate("CreateMasterdatabase", "Select minimum file size in MBytes"))
        self.SizeLimitCombo.setItemText(0, _translate("CreateMasterdatabase", "0"))
        self.SizeLimitCombo.setItemText(1, _translate("CreateMasterdatabase", "10"))
        self.SizeLimitCombo.setItemText(2, _translate("CreateMasterdatabase", "100"))
        self.SizeLimitCombo.setItemText(3, _translate("CreateMasterdatabase", "250"))
        self.SizeLimitCombo.setItemText(4, _translate("CreateMasterdatabase", "500"))
        self.SizeLimitCombo.setItemText(5, _translate("CreateMasterdatabase", "1000"))
        self.movieTypeButton.setText(_translate("CreateMasterdatabase", "View All Movie File Types"))
        self.label_4.setText(_translate("CreateMasterdatabase", "Enter file types in format (mpeg) comma separated"))
