
# This file has been created to make use of the .py file generated by the following command run from the command line
# pyuic5 -o newfile.py MainWindow.ui
# MainWindow.ui is created by designer and is an xml file
# the pyuic command generates a .py equivalent file but you must not change any aspect of this file as when
# you change the gui it rewrites the file and you lose the changes
# The correct approach is to create a file like this one that subclasses the Ui_MainWindow,
# which is the class created in
# MainWindow.py, you must take care to note the class of object that the gui file is based on.
# MainWindow is based on QTWidgets.QMainWindow but it could easily be based on just QTWidgets as you will see from
# the database example. The main window has the main menu and will have lots of signals and slots associated with it
# In this example we use the database screen to show after clicking a button
# To do this we need to import and other files and classes that the button click references
# getMasterdb is a file created to access getDbWidow class, this being the class that manages the gui created by
# py designer

# pyuic5 -o CreateMasterdatabase.py CreateMasterDatabase.ui
# pyuic5 -o MainWindow.py MainWindow.ui
# pyuic5 -o FFMpeg.py ffmpeg.ui
# pyuic5 -o moveNewFiles.py moveNewFiles.ui
# pyuic5 -o GroupAnalysis.py GroupAnalysis.ui


# Note ------this pyuic5 is not really necessary. Its good practice on larger projects to do this as it keeps the ui code separate from the logic code
# for smaller projects its not necessary, as shown in Music.py you can manually create the .py file subclassling the window and then just add the logic
# its quicker as you dont need to keep running pyuic5 each time you modify the ui



# from RenameSystem import Ui_MovieFileRename
from GroupAction import getGroupWindow
from distributeMovies import getDistWindow
from MainWindow import Ui_MainWindow        # MainWindow is the file created by pyuic, Ui_M.. is a class in that file
from PyQt5 import QtWidgets
from getMasterdb2 import getDbWindow         # because we open this window up
from renamefetch import getChangeWindow
from MovieEdit import movieFFMPEG               # movieedit is the pyfile i created with my dev code
                                                # movieFFMPEG is the class that sets up the window in my dev code

class getWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # class super subclasses QtWidgets.QMainWindow on which the form is based

        # in the init phase, preceds all new creations with self. to make them accessible from anywhere
        # next 2 actions are critical to setting up the gui that we created
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # when we created the menu button the signal 'actionBuild_Master' was automatically created
        # here we reference it to run the method below that opens the database window when the button is clicked
        # rt click menu option in the main window ui and it will show the name of the action it created

        self.ui.actionBuild_Master.triggered.connect(self.opendb)   # opendb is the method calling the db GUI

        self.ui.actionRename_Files.triggered.connect(self.openrename)  # opendb is the method calling the rename ops

        # reminder - right click menu option ui to see the action event that the ui automatically creates
        # and refer to it here pointing to the method that calls the window that I need openff
        self.ui.actionFFMpeg_Actions.triggered.connect(self.openff)     # open ffmpeg panel


        # Menu item to distribute new copies
        self.ui.actionDistribute_Copies.triggered.connect(self.moveFiles)

        self.ui.actionFile_Group_Analysis.triggered.connect(self.groupFiles)


    # this method displays the database GUI

    # @staticmethod
    def opendb(self):

        # The window is disappearing because it goes out of scope . Since there are no further references to it,
        # the python garbage collector removes it.
        # Usually PyQt objects keep references to their children so this is not a problem. Since you want the widget
        # to open in a separate window, you can't assign it a parent,
        # so you need to store a reference to it somewhere else. The obvious candidate is the MainWindow class.
        # You can make it a member of MainWindow by using self.myWin = getDbWindow() .
        self.mywin = getDbWindow()
        self.mywin.show()


    def openrename(self):
        self.renWindow = getChangeWindow()
        self.renWindow.show()


    def openff(self):
        self.ffWin = movieFFMPEG()          # create var that references the class I developed
                                            # , its init sets up the view
        self.ffWin.show()                   # then show it


    def moveFiles(self):
        self.mvMovies = getDistWindow()
        self.mvMovies.show()

    def groupFiles(self):
        self.grMovies = getGroupWindow()
        self.grMovies.show()